logo_title: Pcrab 的日常

style: white

favicon: /favicon.ico

menu:
  #作品: /project
  #域名: /domain
  #友联: /links
  关于: /about
  #Github: https://github.com/sanjinhub

# 做了域名限制，请改成自己的 KEY
valine:
  appid: JYGJAIgDkSKSDgp5pUPfyxoO-MdYXbMMI
  appkey: T36nhlVVvMa1c33Tee3F13JM

highlight:
  enable: true
